const zodiacSigns = [
    "Aries",
    "Tarus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarious",
    "Pisces",
]

const Signs = [
     {
        name: "Aries",
        planet: "Mars",
        element: "Fire",
        nature: "Movable",
        gender: "Male",
        varna: "Kshatriya",
        ascension: "Short",
        rises: "Hind",
        direction: "Northern",
        type: "Quadruped",
        fertility: "Barren",
        bodyPart: "Head",
    },
    {
        name: "Taurus",
        planet: "Venus",
        element: "Earth",
        nature: "Fixed",
        gender: "Female",
        varna: "Vaishya",
        ascension: "Short",
        rises: "Hind",
        direction: "Northern",
        type: "Quadruped",
        fertility: "Fruiteful",
        bodyPart: "Face & Throat",
    },
    {
        name: "Gemeni",
        planet: "Mercury",
        element: "Air",
        nature: "Dual",
        gender: "Male",
        varna: "Shudra",
        ascension: "Short",
        rises: "Head and Hind",
        direction: "Northern",
        type: "Human",
        fertility: "Barren",
        bodyPart: "Shoulders & Chest",
    },
    {
        name: "Cancer",
        planet: "Moon",
        element: "Water",
        nature: "Movable",
        gender: "Feale",
        varna: "Brahmin",
        ascension: "Long",
        rises: "Head",
        direction: "Northern",
        type: "Reptile",
        fertility: "Fruiteful",
        bodyPart: "Heart",
    },
    {
        name: "Leo",
        planet: "Sun",
        element: "Fire",
        nature: "Fixed",
        gender: "Male",
        varna: "Kshatriya",
        ascension: "Long",
        rises: "Head",
        direction: "Northern",
        type: "Quadruped",
        fertility: "Barren",
        bodyPart: "Stomach & Upper Abdomen",
    },
    {
        name: "Virgo",
        planet: "Mercury",
        element: "Earth",
        nature: "Dual",
        gender: "Female",
        varna: "Vaishya",
        ascension: "Long",
        rises: "Head",
        direction: "Northern",
        type: "Human",
        fertility: "Barren",
        bodyPart: "Waist & Intestines",
    },
    {
        name: "Libra",
        planet: "Venus",
        element: "Air",
        nature: "Movable",
        gender: "Male",
        varna: "Shudra",
        ascension: "Long",
        rises: "Head",
        direction: "Southern",
        type: "Human",
        fertility: "Moderate",
        bodyPart: "Below Navel",
    },
    {
        name: "Scorpio",
        planet: "Mars",
        element: "Water",
        nature: "Fixed",
        gender: "Female",
        varna: "Brahmin",
        ascension: "Long",
        rises: "Head",
        direction: "Southern",
        type: "Reptile",
        fertility: "Fruiteful",
        bodyPart: "Genitalia",
    },
    {
        name: "Sagittarious",
        planet: "Jupiter",
        element: "Fire",
        nature: "Dual",
        gender: "Male",
        varna: "Kshatria",
        ascension: "Long",
        rises: "Hind",
        direction: "Southern",
        type: "Half Human & Half Quadruped",
        fertility: "Fruiteful",
        bodyPart: "Thighs",
    },
    {
        name: "Capricorn",
        planet: "Saturn",
        element: "Earth",
        nature: "Movable",
        gender: "Female",
        varna: "Vaishya",
        ascension: "Short",
        rises: "Hind",
        direction: "Southern",
        type: "Quadruped",
        fertility: "Moderate",
        bodyPart: "Knees",
    },
    {
        name: "Auarious",
        planet: "Saturn",
        element: "Ait",
        nature: "Fixed",
        gender: "Male",
        varna: "Shudra",
        ascension: "Short",
        rises: "Hind",
        direction: "Southern",
        type: "Human",
        fertility: "Moderate",
        bodyPart: "Ankles",
    },
    {
        name: "Pisces",
        planet: "Jupiter",
        element: "Water",
        nature: "Dual",
        gender: "Male",
        varna: "Brahmin",
        ascension: "Short",
        rises: "Head and Hind",
        direction: "Southern",
        type: "Reptile",
        fertility: "Fruiteful",
        bodyPart: "Feet",
    },
]

const Houses = [
    {
        name: "House1", 
        attribs: [
            "Confidence", "SelfEsteem", "Appearance", "Health", "Character", "Purpose of Life", "Behavior", "Birth", "imbs","Head"
        ],
    },
    {
        name: "House2", 
        attribs:  ["Wealth", "Family", "Domestic Comforts", "Early Education", "Inheritance", "Speech", "moveable assets"],
    },
    {
        name: "House3", 
        attribs: ["Younger Brothers", "Younger Sisters", "Communication", "Talking", "Writing", "Business Documents", "Intelligence", "fine arts", "Short Journeys", "great prowess", "hands", "arms", "shoulders"],
    },
    { 
        name: "House4", 
        attribs: ["Mother", "Emotions", "Education", "Home", "Property and Land", "Surrounding in Old Age", "vehicles","chest"],
    },
    { 
        name: "House5", 
        attribs: ["Children", "Lovers", "Recreation", "Devotion", "Speculation and Gambling", "belly", "accumulated karma"],
    },
    {
        name: "House6", 
        attribs: ["Diseases", "Maternal uncle and aunt", "Litigation", "Servants", "Mental Worries", "Enemies", "Foreigners", "small intestine"],
    },
    {
        name: "House7", 
        attribs: ["Spouse", "Business Partner", "Death", "Respect","Passion", "groin"],
    },
    { 
        name: "House8", 
        attribs: [ "Death & Longevity", "Obstacles", "Suffering", "Sexual organs",  "Sexual attractiveness", "Occult", "Dowry", "Inheritance", "Imprisonment", "Excretory organs", "Accidents"],
    },
    {
        name: "House9", 
        attribs: ["Father", "Luck", "Higher learning", "Philosophy", "Religion", "Mentor", "Prosperity", "Travel", "deeds of virtue"],
    },
    {
        name: "House10", 
        attribs: ["Profession", "Status", "Fame", "Power", "Father", "Mother-in-law", "Government", "Clothes", "Commerce","knees"],
    },
    {
        name: "House11", 
        attribs: ["Friends", "Hopes", "Earnings", "Social Activities", "Elder Brothers", "Elder Sisters", "Daughter", "Son-in-law", "calves", "shins", "Ankles"],
    },
    {
        name: "House12", 
        attribs: ["Expenses", "Sleep", "convalescence", "Sexual pleasures", "Spirituality", "Travel", "Pilgrimage", "Secret Enemies", "Imprisonment", "Hospitals", "Asylums", "Liberation", "Loss", "Foreign residency", "feet"],
    },
]

const Planets = [
    {
        name: "Sun",
        governance: "soul",
        status: "royal",
        gender: "male",
        element: "",
        temperament: "calm",
        nature: "malefic",
    },
    {
        name: "Moon",
        governance: "mind",
        status: "royal",
        gender: "female",
        element: "",
        temperament: "calm",
        nature: "benefic or malefic",
    },
    {
        name: "Mars",
        governance: "mind",
        status: "chief",
        gender: "male",
        element: "fire",
        temperament: "inert",
        nature: "malefic",
    },
    {
        name: "Venus",
        governance: "semen",
        status: "minister",
        gender: "female",
        element: "water",
        temperament: "dynamic",
        nature: "benefic",
    },
    {
        name: "Mercury",
        governance: "speach",
        status: "prince",
        gender: "neuter",
        element: "earth",
        temperament: "dynamic",
    },
    {
        name: "Jupiter",
        governance: "knowledge",
        status: "minister",
        gender: "male",
        element: "space",
        temperament: "calm",
        nature: "benefic",
    },
    {
        name: "Saturn",
        governance: "grief",
        status: "army",
        gender: "neuter",
        element: "air",
        temperament: "inert",
        nature: "malefic",
    },
    {
        name: "Rahu",
        governance: "",
        status: "army",
        element: "",
        temperament: "",
        nature: "malefic",
    },
    {
        name: "Ketu",
        governance: "",
        status: "army",
        element: "",
        temperament: "",
        nature: "malefic",
    }
]
export var ascAngleToSign = function(angle) {
    var signNum = Math.round((angle%360)/30);
    var sign = Signs[signNum].name;
    return sign;
}

export var getRulingPlanet = function(sign) {
    var planet = Signs[sign].planet; 
    return planet;
}